[package]

name = "two_three"
description = "A two-three (2-3) tree implementation in Rust. Includes a map and set interface"
version = "0.0.1"
authors = ["Corey Farwell <coreyf@rwell.org>"]
license = "Apache-2.0"
